[package]
edition = "2018"
name = "bowot"
version = "1.0.0"

[dependencies]
chrono = "0.4.19"
comfy-table = "1.4.2"
failure = "0.1.8"
fasteval = "0.2.4"
futures = "0.3.8"
humantime = "2.0.1"
loc = "0.5.0"
num-format = "0.4.0"
qrcode = "0.12.0"
rand = { version = "0.7.3", features = ["getrandom", "std"] }
regex = "1.4.2"
reqwest = { version = "0.10.9", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
tokio = { version = "0.2.22", features = ["full"] }
toml = "0.5.7"
tracing = "0.1.22"
tracing-log = "0.1.1"
tracing-subscriber = "0.2.15"
tracing-futures = "0.2.4"
walkdir = "2.3.1"
wither = { version = "0.9.0-alpha.2", default-features = false, features = ["tokio-runtime"] }
youtube_dl = { git = "https://github.com/saanuregh/youtube-dl-rs.git", branch = "async" }
itconfig = "1.0"
lazy_static = "1.4"
serenity_utils = "0.5.1"
strsim = "0.10.0"
html-escape = "0.2.6"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
# rev = "b98424d382f54318b4999ccab4d59acb34449df8"
# version = "0.9.2"
default-features = false
features = [
	"builder",
	"cache",
	"client",
	"framework",
	"gateway",
	"http",
	"model",
	"standard_framework",
	"utils",
	"rustls_backend",
	"absolute_ratelimits",
	"collector",
	"voice",
]

[dependencies.songbird]
features = ["builtin-queue"]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
# rev = "f222ce99696ab0dfa396bd6448bb4340b791625b"
