name: Awake

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://bowot69.herokuapp.com/health"
