name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GCLOUD_SERVICE_KEY: ${{ secrets.GKE_SA_KEY }}
  GOOGLE_PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: raccoondev/push-docker-gcr
        with:
          gcr_host: eu.gcr.io
          image_name: bowot
          image_tag: latest
